name: habit_tracker_minimal
description: "A new Flutter project."

publish_to: 'none' # Previene publicaci칩n accidental en pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter_spinner_time_picker: ^0.2.1
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  flutter_local_notifications: ^9.0.0
  flutter_native_splash: ^2.3.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # Si us치s im치genes o fuentes personalizadas, agregalas ac치:
  # assets:
  #   - assets/images/
  #
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: fonts/Raleway-Regular.ttf
